### ISSUE TITLE
Issue with pagination in Cassandra service

### ISSUE THREAD

**Issue by jamsheer-thottathil** [dreamfactorysoftware/dreamfactory#115]
Created service with Cassandra tables and accessed successfully.

I am getting issues while accessing above service with pagination parameters limit and offset.

Same working for mysql but getting issue with Cassandra configuration

It seems limit working fine but offset has issue .

**Comment by df-arif** [comment]
@jamsheer-thottathil, Offset doesn't work for Cassandra service because it is not natively supported by CQL. There are other ways you can do pagination in Cassandra. Here is one example: http://docs.datastax.com/en/cql/3.0/cql/cql_using/paging_c.html . However, this talks about using the token() function which the current beta version of DreamFactory Cassandra service doesn't support yet. We will add support for this in future releases.

**Comment by jamsheer-thottathil** [comment]
thank you for the response
