### ISSUE TITLE
always_wrap_resources => false breaks ui

### ISSUE THREAD

**Issue by tkald** [dreamfactorysoftware/dreamfactory#130]
When I set **always_wrap_resources => false** in config/df.php, ui breaks. 

For example in services - service types list is empty, roles - [select role] - access tab component list is empty...

version 2.4.1

**Comment by drewpearce** [comment]
This is because the "UI" is an application built on DreamFactory, the DF Admin App. It was built assuming that the items coming back from calls like listing roles would be wrapped in the resource wrapper. 
DreamFactory itself can function just fine without these wrappers, but the admin application cannot.
