### ISSUE TITLE
Why did you guys remove MS SQL from the free version.? 

### ISSUE THREAD

**Issue by damionx7** [dreamfactorysoftware/dreamfactory#239]
I just updated to beta 3. And it shows unsupported ms sql. My all databases are gone.

**Comment by wjgilmore** [comment]
Hi @damionx7 Microsoft SQL Server has not been part of the free edition for several years now. We moved it into our paid edition back in 2017 (I think it was 2017) because maintaining and supporting these connectors is extraordinarily time consuming and expensive. You are certainly free to continue running the version of DreamFactory you were running previously, just keep in mind we have made hundreds of improvements and bug fixes since those early releases.

**Comment by isreehari** [comment]
For sure @damionx7 means MySQL.

**Comment by wjgilmore** [comment]
Hi @isreehari if he is running an older version of DreamFactory then he could very well be referring to Microsoft SQL Server. 

However you are correct, MySQL was removed from 3.0 because we are unable to continue dedicating the resources necessary to maintain the free connector. We put thousands of hours into maintaining DreamFactory, and doing so is very expensive. Of course, all users are free to continue using the MySQL connector found in earlier versions of DreamFactory.

**Comment by isreehari** [comment]
Thank you @wjgilmore and I agreed but It would be nice if someone from your team would give notification beforehand. 

I am bringing the following article to your attention. 

--http://community.dreamfactory.com/t/dear-all-df-fans-version-3-0-is-released-with-wings-cut-open-source-will-be-killed-shortly/5005 

"Dear All DF Fans !

Have you guys seen that the DF team has moved two very popular features to their paid plan without making a formal announcement?

MySQL service - The most popular database in the world. Now its needed to pay to use this service.

Custom scripting - Without which you will not be able to write any pre & post scripts, which means you will not be able to customize anything on the open source version. This is now a paid solution.

Basically your DF which you loved is a bird which cannot fly unless you pay!

I feel hurt.

Not because its paid, but because of the lack of transparency and open-ness.

Firstly, If the company is releasing an open source version, they should at-least have a open mentality to inform their users about this major change.From last 3 months, there aren’t any company support on the community forum for any major bug fixes of any sort.

Secondly, the developers would not be able to use old code in new version 3.0 because of the complexity. In-fact the last major 2.14 release has major scripting bugs which makes it unusable too. The strangest thing is : no one in the forum from the company is replying!

Like many open source products we see in the market, this great product will lose its greatness just because they are slowly killing it.

I have been a great fan of this product, but unfortunately, they have just begun to kill it. Its a sad day today.

Comments ?"

**Comment by wjgilmore** [comment]
Hi @isreehari we are a very small team and other than a quick blog post haven't even found the time to "officially" announce the release. You are correct though I will update the blog post to make very clear that MySQL and scripting has been removed. However I can assure you this has nothing to do with a lack of transparency. It is due to expenses and time. 

Regarding the claim of major scripting bugs in 2.14, this is news to me. I've just double checked our JIRA issue tracker and can confirm we have not had a single report from users regarding 2.14 scripting bugs. As for the community forum, you are correct we do not actively police it simply because of the aforementioned time issue. However any other community user is of course free to help others out.

Please keep in mind that DreamFactory 3.0 is still an extraordinarily powerful solution, with a brand new interface, new installers, and many bugs fixed. And it's all free for anybody to use. We certainly welcome contributions from the community as well, so by all means if you find a bug and would like to submit a fix, we welcome the pull request.

**Comment by isreehari** [comment]
@wjgilmore thank you and really appreciated your time.

**Comment by wjgilmore** [comment]
Hi @isreehari I certainly appreciate your input as well. I've updated the blog post: https://blog.dreamfactory.com/introducing-dreamfactory-3/. Again, we certainly value any contributions you can make to the platform, including the documentation! Have you by chance seen the guide we published a few months ago? https://guide.dreamfactory.com The guide repository is found here: https://github.com/dreamfactorysoftware/dreamfactory-book. Contributions welcomed!

**Comment by isreehari** [comment]
Thank you.

**Comment by damionx7** [comment]
> For sure @damionx7 means MySQL.

yes, i mean MYSQL

**Comment by damionx7** [comment]
i moved to django. btw thanks for such great product 👏 👏
