### ISSUE TITLE
Unable to using OCI8 Oracle connection - (Bitnami Windows Installer)

### ISSUE THREAD

**Issue by amader** [dreamfactorysoftware/dreamfactory#25]
Hi all,

i have the problem that i get an error if i will activate the OCI8 extension in php.ini

Error message:
"PHP Warning:  PHP Startup: oci8: Unable to initialize module\nModule compiled with build ID=API20121212,TS,VC11\nPHP    compiled with build ID=API20121212,TS,VC12\nThese options need to match\n in Unknown on line 0"

At the moment there is no possibility to connect to a oracle database.

Please can you help me with this issue.

Thank you 
Best regards
Alex

**Comment by MSchaer1985** [comment]
@amader The latest release from Bitnami, PHP was compiled with Visual C++ 12 rather than version 11. All of the PHP drivers are compiled with version 11. We're working with Bitnami to see about a re-release of this version. In the mean time, if you do not have a need for server side scripting, you can install version 2.0.2 (link below) of the Bitnami stack and then upgrade the DreamFactory code using the instructions on our wiki. This will get you to the latest codebase but still on the compatible architecture. 2.0.2 link: https://bitnami.com/redirect/to/84004/bitnami-dreamfactory-2.0.2-0-windows-installer.exe?bypassauth=false&fb=1&with_popup_skip_signin=1 Upgrade Instructions: http://wiki.dreamfactory.com/DreamFactory/Installation#Windows

**Comment by cosmocracy** [comment]
(Just chiming in that reverting to 2.0.2 worked for me with similar issue #24)  Thanks!

**Comment by drewpearce** [comment]
This is fixed in the latest release from Bitnami, 2.0.4-1.
