### ISSUE TITLE
Could not find a service for user

### ISSUE THREAD

**Issue by MrPhilbert** [dreamfactorysoftware/dreamfactory#3]
Installed into wamp. Configured a name in hosts file. Setup a vhost (dreamfactory.dev). Setup a database.
Initial setup created the tables in mysql but when trying to create the initial user got error "NotFoundException in Service.php line 263:
Could not find a service for user"

I queried the user table and no user is being created on form submission.
I can also confirm that the cache directory is being written to as well as session files are being written.

Thanks

**Comment by kofrezo** [comment]
+1 I can confirm that and have the same problem.

**Comment by leehicks** [comment]
@MrPhilbert Can you run the following commands in the install directory (these should have been automatically run on first page hit, but seems something failed to complete in your install)...

> php artisan migrate (should have completed already due to there being tables in the database, just make sure there are no errors given here)

> php artisan db:seed (this sets up the default entries in the db, one of which is a "user" service for registering users.

Also check the logs in the storage/logs directory and note here any errors you see.

**Comment by jstablesdf** [comment]
DreamFactory 2.0 has performed a GA release since this issue was raised. Please reopen and describe how to replicate the issue if it persists in the current release.

**Comment by SoulTransfer** [comment]
Problem still exists
Steps to reproduce:
1. Install XAMPP
2. Clone Dreamfactory Repo
3. Setup Dreamfactory Repo
4. Setup VirtualHost:
<VirtualHost *:80>
    ServerAdmin webmaster@example.com
	DocumentRoot "C:/DEV/xampp/dreamfactory/public"
	ServerName dreamfactory.localhost
</VirtualHost>
5. Open URL http://dreamfactory.localhost
ERROR:
Could not find a service for dreamfactory

I also created a VirtualDirectory Alias to use instead of the VirtualHost.. and it works!

**Comment by saminanirmala** [comment]
Please help me to solve  Could not find a service for user since i am not able to do anything because of this. What steps i should take to get rid of this?? I am new to dreamfatory laravel

**Comment by drewpearce** [comment]
Since no details were given I can only speculate as to the cause of your issue. If yours is similar to SoulTransfer's issue, that appears to be a case of an improper virtualhost config. We have detailed instructions for configuring Apache in our documentation ( http://wiki.dreamfactory.com/DreamFactory/Installation )
You may want to check that out and see if it addresses your need.

DreamFactory provides free support for new users for 14 days via chat and email ( https://www.dreamfactory.com/support )
We also provide perpetual free support in our community forums ( http://community.dreamfactory.com/ )
Please address support requests via normal support channels and reserve GIthub Issues for logging bugs.
The bug originally raised in this issue has been addressed. If it turns out there is a new bug relating to this, we'll be happy to reopen the issue.
