### ISSUE TITLE
Node.js script hangs when make connection to Cassandra or Redis

### ISSUE THREAD

**Issue by DawoonC** [dreamfactorysoftware/dreamfactory#73]
Hi

I'm trying to use Cassandra and Redis with server-side scripting (Node.js)
Everything works great until I make connection to either Cassandra or Redis.
But when connection is made, the script hangs and does not give any response.

It seems script engine is waiting for Node.js event loop is empty, because it immediately responded when I threw exception in a callback function (but this does not give response I want).

So I'm wondering if there is a way to make response without waiting for event loop to be empty.
(Or a way to make this work if it's not an event loop issue)

~~~javascript
e.g.

// maybe like this?
event.waitForEmptyEventLoop = false;

redis.get('key', function(err, data) {
  if (err) {
    event.response.status_code = 500;
    event.response.content = 'some error...';
  } else {
    event.response.content = data;
  }
});
~~~

**Comment by df-arif** [comment]
If this is hanging the http api call then you need to quit the redis client. do `reis.quit()` at the end.

**Comment by DawoonC** [comment]
@df-arif Thanks for the tip!
Actually yesterday, I found out that setting `event.response.content` inside the callback does not return my data, so I was going to ask about it lol

Thanks again and hope it works out soon :)

**Comment by df-arif** [comment]
@DawoonC, `console.log(JSON.stringify(_event));` is important. It passes your Node.js scripts output to PHP side. We already do this in the code so that if you return anything from your script it goes to PHP side. However, in this case you are inside a callback and therefore need to send the output to PHP side manually. Even though Node.js makes the redis call asynchronously, the script runs in a single PHP process synchronously.
