### ISSUE TITLE
Different Installs handle SQL Server Differently

### ISSUE THREAD

**Issue by lquessenberry** [dreamfactorysoftware/dreamfactory#82]
I installed the Mac OSX Bitnami version of DreamFactory and was able to successfully connect to our SQL Server 2012 box in our local network. I have since followed instructions in the README for installing from GitHub on our web server (Ubuntu) and I now have DreamFactory set up, but when I choose SQL Server it tells me I need a subscription to connect to an SQL server. :( 

Why is there a difference? Is it because I installed via composer and the --no-dev option?

**Comment by drewpearce** [comment]
Hi Lee. Beginning with DreamFactory 2.2, several services are no longer included in the free open source package, including MS SQL. (see the changelog here: https://github.com/dreamfactorysoftware/dreamfactory/blob/master/CHANGELOG.md )

Since Bitnami has not yet packaged v 2.2 they are still distributing the previous version, which you are of course free to use in perpetuity with SQL server.
